name: Backend CI Checks

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['main', 'develop']

jobs:
  lint-format-check:
    name: Lint & Format Check
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      # 1. Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js environment
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # 3. Install dependencies using 'npm ci' (clean install based on lock file)
      - name: Install dependencies
        run: npm ci

      # 4. Run ESLint checks using the script defined in package.json
      - name: Run ESLint check
        run: npm run lint

      # 5. Run Prettier format check using the script defined in package.json
      - name: Run Prettier format check
        run: npm run format:check
